.\"	$OpenBSD$
.\"
.\" Copyright (c) 2024 Kirill A. Korinsky <kirill@korins.ky>
.\" Copyright (c) 2019 Martijn van Duren <martijn@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt FILTER-DNSBL 8
.Os
.Sh NAME
.Nm filter-dnsbl
.Nd block senders based on dnsbl
.Sh SYNOPSIS
.Nm
.Op Fl mv
.Op Fl w
.Op Fl d
.Op Fl e Ar IPv4
.Ar blacklist
.Ar ...
.Sh DESCRIPTION
.Nm
looks up the IP address of the sender in the
.Ar blacklist
.Pq a domain name
and, by default drops the connection if it is found. The expected IPv4
address in the DNS response can be specified with the
.Fl e
argument before
.Ar blacklist .
If the
.Fl m
flag is specified, it will allow the message to continue, but such a
message will be marked with
.Em X-Spam
header with value
.Em Yes ,
and
.Em X-Spam-DNSBL
header containing a list, and any existing headers starting with
.Em X-Spam
will be stripped. If the
.Fl w
flag is specified before
.Ar blacklist ,
this list is treated as white list and
.Em X-Spam
header isn't added, but
.Em X-Spam-DNSWL
header is added instead
.Em X-Spam-DNSBL .
Additionally, if the
.Fl d
flag is specified before
.Ar blacklist ,
it will use reverse DNS hostname instead of IP address for loopkup. For
more verbose logging, the
.Fl v
flag can be used.
.Pp
When DNS error happened it drops the connection, or adds
.Em X-Spam
header with value
.Em Unknown
and
.Em X-Spam-DNS
with a list with cause an error if the
.Fl m
flag is specified.
.Pp
Lists matching the IP address or doamin are echoed back to the sender.
Paid services from Abusix and Spamhaus have their key stripped.
.Sh SEE ALSO
.Xr smtpd 8
